### ISSUE TITLE
Support Swipe-to-Dismiss behavior

### ISSUE THREAD

**Issue by Perfomer** [usuiat/Zoomable#184]
**Feature request:**
I would like to ask it is possible to support Swipe-to-Dismiss behavior in Zoomable library?

I see the API like this:
```kotlin
val zoomState = rememberZoomState()

Modifier.zoomable(
    zoomState = zoomState,
    // enables behavior
    enableDismissGesture = true,
    // callback for progress listening, may be needed for changing background alpha
    // provides value between 0F and 1F
    onDismissProgressChange = { progress: Float -> Log.d("MyTag", "Dismiss progress $progress") },
    // triggers when progress reaches 1F
    onDismiss = { Log.d("MyTag, "Dismissed" },
),
```

Similar behavior you can see in Telegram or at the video:

https://github.com/usuiat/Zoomable/assets/16479387/e1769b4c-95d9-4528-b8f3-7dafcffce9ab

**Comment by usuiat** [comment]
Thank you for your suggestion.
It’s interesting to implement swipe-to-dismiss as a library.

However, I think swipe-to-dismiss should be provided as an independent feature from zoomable, so I would not add it to this library.

FYI
Zoomable can be used in conjunction with gesture detection modifiers such as dragable, since zoomable makes PointerEvents transparent that it does not consume.
You can implement your own swipe-to-dismiss and use it in conjunction with zoomable.
