### ISSUE TITLE
Min/Max scale

### ISSUE THREAD

**Issue by T8RIN** [usuiat/Zoomable#193]
is it possible to Expose maxScale property and also add minScale?

**Comment by usuiat** [comment]
@T8RIN 
Thank you for the issue and the pull request.
I have two requests.

1) Can you tell me why minScale and maxScale are needed?
I made these properties private because I could not imagine a use case where the properties would be used externally.
If you have a specific use case in mind, please let me know.

2) Please make one PullRequest for one Issue.

**Comment by T8RIN** [comment]
I want to create custom double tap handler so it will work as tri state one, but there we really need max scale and minscale to calculate center one

**Comment by usuiat** [comment]
Thanks, I understand.
I agree to change maxScale to public.
However, it is difficult to change minScale to public. This is because zoomable is implemented with the assumption that minScale=1. Allowing arbitrary minScale would require significant implementation changes.

**Comment by T8RIN** [comment]
Okay
