### ISSUE TITLE
How to zoom at the center of the image programmatically

### ISSUE THREAD

**Issue by hellosagar** [usuiat/Zoomable#203]
I've take a look at this [PR](https://github.com/usuiat/Zoomable/issues/190). According to this I can use
``` kotlin
zoomState.changeScale(
     zoomstate.scale * 2,
     Offset(X,Y),
)
```
Where X and Y would be if I understood it correctly. @usuiat  Is the formula looks correct to you?
```
X = (w∗scale−w)/2
Y = (h∗scale−h)/2
```

Currently cant access the layout size from the `zoomState`. How can I achieve this?

**Comment by hellosagar** [comment]
Currently, on passing the same offset, it behaves like the following.
```
zoomState.changeScale(
                zoomState.scale + 1,
                Offset(zoomState.offsetX, zoomState.offsetY),
              )
```

https://github.com/usuiat/Zoomable/assets/50016799/ad772ba5-26bd-43e1-89d8-ec6861381ee0



@usuiat I would appreciate your response. Thanks!

**Comment by usuiat** [comment]
@hellosagar 
One possible way to achieve this is `Modifier.onSizeChanged`.
You can get the size of image like below.

```Kotlin
var size = remember { Size.Unspecified }
Image(
    ...
    modifier = Modifier
        .onSizeChanged { size = it.toSize() }
        .zoomable( ... )
)
```

Then you can pass `size.center` to `ZoomState.changeScale`.

```Kotlin
zoomState.changeScale(
    targetScale = 2f,
    position = size.center
)
```

By the way, I am wondering if I should make `ZoomState.layoutSize` public.
Because it is not available at the time `ZoomState` is created.
